name: update
description: Check for new versions of Yagna
runs:
  using: composite
  steps:
    - shell: sh
      run: |
        curl -sS https://join.golem.network/as-provider > install.sh
        YA_CORE_VERSION=$(cat install.sh | sed -nE 's/^.*YA_INSTALLER_CORE="?\$\{YA_INSTALLER_CORE:-v([^}]+)\}"?.*$/\1/p')
        YA_WASI_VERSION=$(cat install.sh | sed -nE 's/^.*YA_INSTALLER_WASI="?\$\{YA_INSTALLER_WASI:-v([^}]+)\}"?.*$/\1/p')
        YA_VM_VERSION=$(cat install.sh | sed -nE 's/^.*YA_INSTALLER_VM="?\$\{YA_INSTALLER_VM:-v([^}]+)\}"?.*$/\1/p')
        sed -i -E 's/(ARG YA_CORE_VERSION=)\S+/\1${YA_CORE_VERSION}/' docker/Dockerfile
        sed -i -E 's/(ARG YA_WASI_VERSION=)\S+/\1${YA_WASI_VERSION}/' docker/Dockerfile
        sed -i -E 's/(ARG YA_VM_VERSION=)\S+/\1${YA_VM_VERSION}/' docker/Dockerfile
